spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader # 转发 host
      routes:
        # 商品 服务
        - id: product
          uri: lb://product
          predicates:
            - Path=/category/**,/brand/**,/attribute/**
